# volumes:
services:
  mrq:
    build:
      context: mrq
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./mrq:/app
    environment:
      DATABASE_URL: postgresql://MRQ:test-databases@postgres/MRQ
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}
